import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';

const ROOT = process.cwd();
const ENV_PATH = resolve(ROOT, '.env');
const OUTPUT_PATH = resolve(ROOT, 'src/environments/environment.generated.ts');

const REQUIRED_KEYS = [
  'TRACKER_API_BASE_URL',
];

function parseDotEnv(content) {
  const env = {};
  const lines = content.split(/\r?\n/);

  for (const rawLine of lines) {
    const line = rawLine.trim();

    if (!line || line.startsWith('#')) {
      continue;
    }

    const equalIndex = line.indexOf('=');
    if (equalIndex <= 0) {
      continue;
    }

    const key = line.slice(0, equalIndex).trim();
    let value = line.slice(equalIndex + 1).trim();

    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }

    env[key] = value;
  }

  return env;
}

const parsed = { TRACKER_API_BASE_URL: '/api', ...(existsSync(ENV_PATH) ? parseDotEnv(readFileSync(ENV_PATH, 'utf8')) : {}) };
for (const key of REQUIRED_KEYS) {
  if (process.env[key]) parsed[key] = process.env[key];
}
const missing = REQUIRED_KEYS.filter((key) => !parsed[key]);

if (missing.length > 0) {
  throw new Error(`Missing required .env keys: ${missing.join(', ')}`);
}

const generated = `// Auto-generated by scripts/generate-env.mjs. Do not edit manually.\n` +
`export const trackerEnv = {\n` +
REQUIRED_KEYS.map((key) => `  ${key}: ${JSON.stringify(parsed[key])},`).join('\n') +
`\n} as const;\n`;

mkdirSync(dirname(OUTPUT_PATH), { recursive: true });
writeFileSync(OUTPUT_PATH, generated, 'utf8');
console.log(`Generated ${OUTPUT_PATH}`);
